Develop_profiles-controller＆edit view
YukiTokieda/freemarket_sample_50c pull request #30
Opened 2019-05-11 09:10 UTC by FUM01ichikawa

# WHAT
・プロフィールコントローラーの作成
（・profiles_controller
→Mypageフォルダに格納
→1行目を下記に修正
class Mypage::ProfilesController < ApplicationController）
・プロフィール編集ページのViewの一部作成

# WHY
・ユーザのプロフィール確認及び変更機能の実装に向け

作成画面
https://gyazo.com/a8ddbec9918356f9eda2205a46504870

予定の完成形はメルカリの↓ページ
https://www.mercari.com/jp/mypage/profile/

2019-05-11 09:27 UTC, A2JA2X commented on app/views/mypage/profiles/_profile-edit.html.haml
> +.container
edit.html.erbというファイルを作成してそこにここの内容をコピペしてください！
またこのファイルの名前をedit.html.hamlにしてください！
不明な点があれば渡辺まで。

2019-05-11 09:40 UTC, FUM01ichikawa commented on app/views/mypage/profiles/_profile-edit.html.haml
> +.container
ファイル名称変更しました〜

2019-05-11 09:41 UTC, A2JA2X commented
LGTM!

2019-05-11 09:52 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^

2019-05-11 09:52 UTC, i-date commented on app/assets/stylesheets/profiles.scss
> +// Place all the styles related to the profiles controller here.
こちらのファイルは不要でしたら削除しましょう。

2019-05-11 09:52 UTC, i-date commented on app/views/mypage/profiles/edit.html.haml
> +.container
こちらのページではフォームを使用しているので、formタグなどを使用してあげましょう。

2019-05-11 09:52 UTC, i-date commented on app/assets/javascripts/profiles.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
こちらのファイルは不要でしたら削除しましょう。

2019-05-12 03:38 UTC, FUM01ichikawa commented on app/assets/stylesheets/profiles.scss
> +// Place all the styles related to the profiles controller here.
ファイルを削除しました

2019-05-12 03:38 UTC, FUM01ichikawa commented on app/views/mypage/profiles/edit.html.haml
> +.container
form_tagを追記しました。（内容は今後追記する形になります。）

2019-05-12 03:39 UTC, FUM01ichikawa commented on app/assets/javascripts/profiles.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
ファイルを削除しました。

2019-05-12 03:43 UTC, FUM01ichikawa commented
念の為、調整版は下記の形になります。（アイコンとname部分の距離を微調整）
https://gyazo.com/23455ec87062f30dd204b01703382e32

2019-05-12 03:46 UTC, ghost requested changes

2019-05-12 03:46 UTC, hiroki5123 commented on test/controllers/profiles_controller_test.rb
> +require 'test_helper'
このファイルは使わないと思うので削除しましょう

2019-05-12 04:03 UTC, FUM01ichikawa commented on test/controllers/profiles_controller_test.rb
> +require 'test_helper'
testファイルに追記しました。残す方向で進めたいです。

2019-05-12 04:09 UTC, kuroko918 commented on app/assets/stylesheets/modules/_profile-edit.scss
> +    background: url(///www.mercari.com//jp/assets/img/mypage/user-bg.jpg?65428115);
こちらはコメントアウトされていますが、必要ありますか？

2019-05-12 04:10 UTC, kuroko918 commented on app/helpers/profiles_helper.rb
> +module ProfilesHelper
このファイルは要らないですね！

2019-05-12 04:11 UTC, kuroko918 commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
画像はいちいちリクエストするのは負担なので、assets/images以下に落としておいて下さい！
それでここで読み込みましょう！

2019-05-12 04:11 UTC, kuroko918 commented
コンフリクトも解除いていて下さい！

2019-05-12 05:03 UTC, FUM01ichikawa commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
アドバイスいただいた通り、該当画像をassets/images以下に格納して対応しました！

2019-05-12 05:05 UTC, FUM01ichikawa commented on app/assets/stylesheets/modules/_profile-edit.scss
> +    background: url(///www.mercari.com//jp/assets/img/mypage/user-bg.jpg?65428115);
///の部分を//に修正しました。（読み込む際に、///→//に自動変換されていました）

2019-05-12 05:05 UTC, FUM01ichikawa commented on app/helpers/profiles_helper.rb
> +module ProfilesHelper
削除しました！

2019-05-12 05:07 UTC, kuroko918 commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
assets/imagesにimageは追加しましたか？
もし追加していたら、github上にもアップし、ここで呼び出すようにしてください！

2019-05-12 05:08 UTC, kuroko918 commented
https://github.com/YukiTokieda/freemarket_sample_50c/pull/30/#discussion_r283119606
こちら確認お願いします！

2019-05-12 05:50 UTC, FUM01ichikawa reviewed
確認のご指示をいただいた点はこちらで間違いないでしょうか？
（因みにgithub上のUpload filesボタンからも上げる方法もやってみたのですが、github desktopから上げたものと表示は同じになりました。）

2019-05-12 05:50 UTC, FUM01ichikawa commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
https://github.com/YukiTokieda/freemarket_sample_50c/pull/30/commits/081b9a2b4d73ca9d2ebc197f9a478bbf376dce1b

Files changedには出てきていませんが、↑で上げています。
これで格納されたという認識だったのですが、方法に間違いがありましたらアドバイスをいただけますと幸いです。

2019-05-12 06:12 UTC, kuroko918 commented
> 確認のご指示をいただいた点はこちらで間違いないでしょうか？
> （因みにgithub上のUpload filesボタンからも上げる方法もやってみたのですが、github desktopから上げたものと表示は同じになりました。）

そもそも、file changesに画像が出てくるんですけどね…
あと読み込む場合は`= image_tag ‘画像のファイル名'`で呼び出せます！

2019-05-12 06:28 UTC, FUM01ichikawa commented
えーと、image_tagで呼び出している7行目の部分（プロフィール画像）についての変更指示という認識でし対応していましたが、8行目〜11行目の中で変更した方が良い部分（image_tagで別途呼びだす必要がある点）がありましたら助言いただきたいです。
↓では画像がアップロードされていない状態でしょうか？
https://gyazo.com/f0f8e1b973ee2dcdf633d44a5033472a

2019-05-12 06:33 UTC, ghost requested changes

2019-05-12 06:33 UTC, hiroki5123 commented on app/assets/stylesheets/modules/_profile-edit.scss
> +  background-color:#FFFFFF;
よく使う色は変数化しましょう

2019-05-12 06:33 UTC, hiroki5123 commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
file changedに出てこないということはこのプルリクエストで修正できてないということになりますので、修正を御願いします。

2019-05-12 06:33 UTC, hiroki5123 commented on test/controllers/profiles_controller_test.rb
> +require 'test_helper'
今回はRspecを使わずにrailsに標準搭載のテストで進めていくという認識で大丈夫ですか？

2019-05-12 06:36 UTC, ghost requested changes

2019-05-12 06:36 UTC, hiroki5123 commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
あー、valueで指定しているんですね。
あとで実装すると思うので一旦ここの部分に関してはこのままで大丈夫です

2019-05-12 07:10 UTC, FUM01ichikawa commented on app/assets/stylesheets/modules/_profile-edit.scss
> +  background-color:#FFFFFF;
ありがとうございます。カラーに関してはチームで相談して変数化を進めたいと思います。
（一旦Viewの完成を進めています。）

2019-05-12 07:10 UTC, FUM01ichikawa commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
7行目のimage_tag部分の画像アップロードですが、git上からのアップロードで下記の通り別のpull requestを作成してみました。↓こちらをマージすると、アップロードされるでしょうか（一応Files changedには表示されています。）
https://github.com/YukiTokieda/freemarket_sample_50c/pull/35

2019-05-12 07:20 UTC, nagatomokent commented on test/controllers/profiles_controller_test.rb
> +require 'test_helper'
上記どうでしょうか、rspecをお勧めします

2019-05-12 07:22 UTC, nagatomokent commented on app/views/mypage/profiles/edit.html.haml
> +        %input{name: "after_save_callback", type: "hidden", value: "https://www.mercari.com/jp/mypage/profile/"}/
確認しました、こちらのprでは画像上がってますね！

2019-05-12 07:22 UTC, nagatomokent commented
テスト方針をrspecにするのかrails標準のものにするのか回答お願いします！

2019-05-13 01:51 UTC, FUM01ichikawa commented
テスト方針はrspecの方向です。（実際の導入は別のプルリクエストになるかと思います。）

2019-05-13 02:09 UTC, TOMARUMARU commented on app/assets/stylesheets/application.scss
> +<<<<<<< HEAD
conflct解消しましょう

2019-05-13 03:25 UTC, FUM01ichikawa commented on app/assets/stylesheets/application.scss
> +<<<<<<< HEAD
解消しました。

2019-05-13 03:36 UTC, TOMARUMARU approved these changes
LGTM

2019-05-13 03:39 UTC, merged